services:
  - type: pserv
    name: isrc-analyzer-postgres
    plan: starter

  - type: web
    name: isrc-analyzer-api
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: isrc-analyzer-postgres
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: LASTFM_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: CORS_ORIGINS
        value: "*"
    healthCheckPath: /api/status
