services:
  # PostgreSQL Database
  - type: pserv
    name: isrc-analyzer-postgres
    env: node
    plan: starter
    
  # Backend API Service
  - type: web
    name: isrc-analyzer-api
    env: python
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: "python run.py"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: isrc-analyzer-postgres
          property: connectionString
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: LASTFM_API_KEY
        sync: false
    
  # Frontend Static Site
  - type: web
    name: isrc-analyzer-frontend
    env: static
    plan: starter
    buildCommand: |
      cd frontend
      npm ci
      npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://isrc-analyzer-api.onrender.com