"""Initial Prism Analytics schema

Revision ID: 3a2ff4ffe400
Revises: 
Create Date: 2025-07-15 21:19:38.983582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a2ff4ffe400'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'musicbrainz_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('artists', 'spotify_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=22),
               existing_nullable=True)
    op.alter_column('artists', 'country',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=2),
               existing_nullable=True)
    op.alter_column('artists', 'youtube_upload_frequency',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('artists', 'youtube_growth_potential',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('artists', 'social_handles',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('artists', 'outreach_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('artists', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('artists', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index('idx_artists_lead_tier', 'artists', ['lead_tier'], unique=False)
    op.create_index('idx_artists_outreach_status', 'artists', ['outreach_status'], unique=False)
    op.create_index('idx_artists_region', 'artists', ['region'], unique=False)
    op.create_index('idx_artists_social_handles_gin', 'artists', ['social_handles'], unique=False, postgresql_using='gin')
    op.create_index('idx_artists_total_score', 'artists', ['total_score'], unique=False)
    op.create_index('idx_artists_youtube_subscribers', 'artists', ['youtube_subscribers'], unique=False)
    op.drop_column('artists', 'last_contacted')
    op.alter_column('contact_attempts', 'contact_method',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('contact_attempts', 'source',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('contact_attempts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index('idx_contact_attempts_artist_id', 'contact_attempts', ['artist_id'], unique=False)
    op.create_index('idx_contact_attempts_confidence', 'contact_attempts', ['confidence_score'], unique=False)
    op.create_index('idx_contact_attempts_method', 'contact_attempts', ['contact_method'], unique=False)
    op.alter_column('outreach_logs', 'method',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('outreach_logs', 'conversion_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('outreach_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index('idx_outreach_logs_artist_id', 'outreach_logs', ['artist_id'], unique=False)
    op.create_index('idx_outreach_logs_contact_date', 'outreach_logs', ['contact_date'], unique=False)
    op.create_index('idx_outreach_logs_conversion_status', 'outreach_logs', ['conversion_status'], unique=False)
    op.add_column('tracks', sa.Column('spotify_id', sa.String(length=22), nullable=True))
    op.add_column('tracks', sa.Column('musicbrainz_id', sa.String(length=36), nullable=True))
    op.alter_column('tracks', 'isrc',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=12),
               existing_nullable=False)
    op.alter_column('tracks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tracks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index('idx_tracks_artist_id', 'tracks', ['artist_id'], unique=False)
    op.create_index('idx_tracks_isrc', 'tracks', ['isrc'], unique=False)
    op.create_index('idx_tracks_release_date', 'tracks', ['release_date'], unique=False)
    op.drop_column('tracks', 'spotify_track_id')
    op.drop_column('tracks', 'musicbrainz_recording_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('musicbrainz_recording_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tracks', sa.Column('spotify_track_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index('idx_tracks_release_date', table_name='tracks')
    op.drop_index('idx_tracks_isrc', table_name='tracks')
    op.drop_index('idx_tracks_artist_id', table_name='tracks')
    op.alter_column('tracks', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tracks', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tracks', 'isrc',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('tracks', 'musicbrainz_id')
    op.drop_column('tracks', 'spotify_id')
    op.drop_index('idx_outreach_logs_conversion_status', table_name='outreach_logs')
    op.drop_index('idx_outreach_logs_contact_date', table_name='outreach_logs')
    op.drop_index('idx_outreach_logs_artist_id', table_name='outreach_logs')
    op.alter_column('outreach_logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('outreach_logs', 'conversion_status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('outreach_logs', 'method',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index('idx_contact_attempts_method', table_name='contact_attempts')
    op.drop_index('idx_contact_attempts_confidence', table_name='contact_attempts')
    op.drop_index('idx_contact_attempts_artist_id', table_name='contact_attempts')
    op.alter_column('contact_attempts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('contact_attempts', 'source',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('contact_attempts', 'contact_method',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('artists', sa.Column('last_contacted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index('idx_artists_youtube_subscribers', table_name='artists')
    op.drop_index('idx_artists_total_score', table_name='artists')
    op.drop_index('idx_artists_social_handles_gin', table_name='artists', postgresql_using='gin')
    op.drop_index('idx_artists_region', table_name='artists')
    op.drop_index('idx_artists_outreach_status', table_name='artists')
    op.drop_index('idx_artists_lead_tier', table_name='artists')
    op.alter_column('artists', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('artists', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('artists', 'outreach_status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('artists', 'social_handles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('artists', 'youtube_growth_potential',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('artists', 'youtube_upload_frequency',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('artists', 'country',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('artists', 'spotify_id',
               existing_type=sa.String(length=22),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('artists', 'musicbrainz_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
